package Edureka;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class AmazonTest {
  private WebDriver driver;

  //Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "driver/chromedriver.exe");
    driver = new ChromeDriver();
    driver.manage().window().maximize();
  }
  //After
  public void tearDown() {
    driver.quit();
  }
  //Test
  public void amazontest() {
    // Test name: amazon_test
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.amazon.fr/");
    // 2 | setWindowSize | 773x421 | 
    driver.manage().window().setSize(new Dimension(773, 421));
    // Cookies bug
    driver.findElement(By.id("sp-cc-accept")).click();
    // 3 | click | id=twotabsearchtextbox | 
    driver.findElement(By.id("twotabsearchtextbox")).click();
    // 4 | click | linkText=Meilleures Ventes | 
    driver.findElement(By.linkText("Meilleures Ventes")).click();
    // 5 | assertTitle | Amazon.fr Les meilleures ventes: Les articles les plus populaires sur Amazon | 
    System.out.println("The page title is : " +driver.getTitle());
    // 7 | click | linkText=Dernières nouveautés | 
    driver.findElement(By.linkText("Dernières nouveautés")).click();
    // 8 | click | linkText=Baromètre des ventes | 
    driver.findElement(By.linkText("Baromètre des ventes")).click();
  }
}
